AWSTemplateFormatVersion: 2010-09-09
Description: Simple ASG with capactiy of 1 instance.
Metadata: This is still a work in progress.

# Parameters:

# Mappings:

# Conditions:

Resources:
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId:
        Ref: myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  singleConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-033b95fb8079dc481 # Latest AML2 AMI
      SecurityGroups:
        - Ref: logicalName
        - myExistingEC2SecurityGroup
      InstanceType: t3.micro

  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - subnetIdAz1
        - subnetIdAz2
        - subnetIdAz3
      LaunchConfigurationName: !Ref singleConfig
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"

Outputs:
